### ISSUE TITLE
Installed it. Now What?

### ISSUE THREAD

**Issue by poraschaudhary** [ascillato/hass-io-addons#1]
Hi,

I installed the add-on in hassio. Now What?

How should I configure it?
![screen shot 2018-10-04 at 7 32 30 pm](https://user-images.githubusercontent.com/42437475/46479261-54a40c00-c80c-11e8-9c5c-3f7d91a53ea2.jpg)

What should I put in config?

Thanks!

**Comment by ascillato** [comment]
Hi,

Nothing.

It start working after run. No extra config needed.

You can set the NTP config of your devices (on your devices) to the IP of your Hassio and just that.
