### ISSUE TITLE
Provide example

### ISSUE THREAD

**Issue by apetitjean** [ascillato/hass-io-addons#2]
Hi,

I successfully installed your add-on in my HA hassio instance but I don't know what to enter in the Config box. Could you please provide an example?

Many thanks for your work.

Arnaud

**Comment by ascillato** [comment]
There is nothing needed in the config box

**Comment by apetitjean** [comment]
Ohhh I didn't understand though. I thought your addon was a NTP client.

Because from my understanding - with HASS.IO -, currently there's no way to
synchronize the time with any NTP source. Right?

Le ven. 18 janv. 2019 à 14:27, Adrian Scillato <notifications@github.com> a
écrit :

**Comment by ascillato** [comment]
Sorry, hassio IS ALREADY IN SYNC with public ntp servers if you have Internet.

This addon is for sharing the time of hassio to other devices like Tasmota

**Comment by apetitjean** [comment]
Really?

It doesn't seem this is the case of my instance (which is running on a
Raspberry Pi).

Do you know where to find the logs?

Le ven. 18 janv. 2019 à 14:31, Adrian Scillato <notifications@github.com> a
écrit :

**Comment by ascillato** [comment]
If your hassio is not syncing the time, check your Internet connection. For further help on that, please go to the home assistant Support chat on Discord

**Comment by apetitjean** [comment]
That's pretty weird because It seems I have no problem with my internet
connection. But thanks!

Le ven. 18 janv. 2019 à 14:35, Adrian Scillato <notifications@github.com> a
écrit :

**Comment by ascillato** [comment]
Yeap. May be a firewall issue or something like that. Mine is syncing the time fine. No issue and my devices then connect to hassio for retrieving the time using this addon and also working fine.

Please, check the chat. They will provide you more help on your issue. Thanks
